name: LikeChat
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.2.1
  image_picker: ^1.1.2
  video_player: ^2.8.6
  video_thumbnail: ^0.5.3
  chewie: ^1.2.2
  camera: ^0.11.0+1
  image: ^4.2.0
  permission_handler: ^11.3.1
  flutter_volume_controller:
  #coneccion
  connectivity: ^3.0.6
  pro_image_editor: ^2.5.8
  iconoir_flutter: ^7.7.0
  flutter_svg: ^2.0.10+1
  volume_controller: ^2.0.7
  lottie: ^3.1.2
  flutter_sliding_up_panel:
  scrollable_positioned_list:
  google_sign_in: ^6.2.1
  network_info_plus: ^5.0.3
  emoji_picker_flutter: ^2.2.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  path:
  socket_io_client: ^2.0.3+1
  dio: ^5.4.3+1
  jwt_decoder: ^2.0.1
  image_cropper: ^7.0.5
  dotted_border: ^2.1.0
  flutter_image_filters: ^0.0.19
  share_plus: ^9.0.0
  carousel_slider: ^4.2.1
  video_trimmer: ^2.1.0
  text_editor: ^0.7.0
  file_picker: ^8.0.6
  url_launcher: ^6.3.0
  agora_rtc_engine: ^6.1.0
  pip_view: ^0.9.7
  wakelock_plus: ^1.2.5
  get: ^4.6.5
  contacts_service: ^0.6.3
  animations: ^2.0.11
  flutter_vibrate: ^1.3.0
  font_awesome_flutter: ^10.7.0
  google_maps_flutter: ^2.7.0
  audioplayers: ^6.0.0
  flutter_sound: ^9.6.0
  flutter_riverpod: ^2.5.1
  ffmpeg_kit_flutter: ^5.1.0-LTS
  multiple_images_picker: ^1.0.1
  flutter_file_downloader: ^2.0.0
  open_file: ^3.3.2
  pdf: ^3.11.0
  pdf_image_renderer: ^0.7.0
  qr_code_scanner: ^1.0.1
  flutter_facebook_auth: ^7.0.1
  youtube_player_flutter: ^9.0.2
  uni_links2: ^0.6.0+2
  #birthday
  flutter_datetime_picker_plus: ^2.2.0
  intl: ^0.18.0
  dropdown_button2: ^2.3.9
  installed_apps: ^1.5.2
  device_apps: ^2.2.0
  #para pagos
  fl_chart: ^0.69.2
  #Fondo borroso
  glassmorphism: ^3.0.0
  #idioma
  #flutter_localization: ^0.2.2
  #save imagen
  image_gallery_saver: ^2.0.3
  #animation_wrappers:
  flutter_animate: ^4.5.2
  #galeria de imagenes
  photo_manager: ^3.6.3
  #authentication
  oauth2: ^2.0.3
  #no salir de la app_links:
  flutter_web_auth: ^0.5.0
  #mas icono
  icons_plus: ^5.0.0
  #desenfoque
  blur: ^4.0.0
  #hasheo verif. de image_editor
  crypto: ^3.0.3
  convert: ^3.1.2
  #patrones del celular
  local_auth: ^2.3.0
  pattern_lock: ^2.0.0

  cached_network_image: ^3.4.0
  sqflite: ^2.3.3+1
  fluttertoast: ^8.2.8
  vibration: ^1.9.0
  google_fonts: ^6.2.1

  #security 2a
  pin_code_fields: ^8.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"

flutter:

  uses-material-design: true
  assets:
    - lib/assets/favorite.svg
    - lib/assets/mesage.svg
    - lib/assets/shared.svg
    - lib/assets/logo.png
    - lib/assets/perro.png
    - lib/assets/placeholder_image.jpeg
    - lib/assets/loading_animation.json

    - lib/assets/logo_google_login.png
    - lib/assets/placeholder_user.jpg
    - lib/assets/placeholder-image.png
    - lib/assets/placeholder_filter.png
    - lib/assets/emoticon.json
    - lib/assets/emoticon2.json
    - lib/assets/angry.json
    - lib/assets/aplausos.json
    - lib/assets/enamo.json
    - lib/assets/Haja.json
    - lib/assets/heart.json
    - lib/assets/like.json
    - lib/assets/sorpresa.json
    - lib/assets/ultima.json

    #loading
    - lib/assets/loading/infinity_cyan.json
    - lib/assets/loading/infinity_blue.json
    - lib/assets/loading/infinity.json
    - lib/assets/loading/loading_infinity.json
    #splash inicio
    - lib/assets/splash/logo_splash.png
    - lib/assets/splash/logo_splash2.png
    - lib/assets/splash/chaski.png
    #success loading
    - lib/assets/succes/success.json

    - lib/assets/avatar/avatar.png

    - lib/assets/LikeChat.gif
    - lib/assets/download.json
    - lib/assets/download1.json
    - lib/assets/downloadel.json
    - lib/assets/descargavideo.json
    - lib/assets/loading-end.json
    - lib/assets/flum_viral.json
    - lib/assets/sounds/toggle_sound.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700
        - asset: assets/fonts/Oswald-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oswald-BoldItalic.ttf
          weight: 500
        - asset: assets/fonts/Oswald-Heavy.ttf
          weight: 400

    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.otf
          weight: 400

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand x.ttf
          weight: 600
        - asset: assets/fonts/Quicksand_Bold.otf
          weight: 700
        - asset: assets/fonts/Quicksand_Bold_Oblique.otf
          weight: 400
        - asset: assets/fonts/Quicksand_Book.otf
          weight: 600
        - asset: assets/fonts/Quicksand_Dash.otf
          weight: 700

    - family: Anton
      fonts:
        - asset: assets/fonts/Anton.ttf
          weight: 400

    - family: Antonella
      fonts:
        - asset: assets/fonts/Antonella.otf
          weight: 400

    - family: Antonellie Callygraphy Demo
      fonts:
        - asset: assets/fonts/Antonellie Callygraphy Demo.otf
          weight: 400

    - family: Antonine Personal Use
      fonts:
        - asset: assets/fonts/Antonine Personal Use.ttf
          weight: 400

    - family: Badgear Script DEMO
      fonts:
        - asset: assets/fonts/Badgear Script DEMO.otf
          weight: 400

    - family: Badrudin-Script
      fonts:
        - asset: assets/fonts/Badrudin-Script.otf
          weight: 400

    - family: BebasNeue-Regular
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.otf
          weight: 500

    - family: Julia Antonio
      fonts:
        - asset: assets/fonts/Julia Antonio.otf
          weight: 400

    - family: Latton
      fonts:
        - asset: assets/fonts/Latton.otf
          weight: 400

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico.ttf
          weight: 500

    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento.ttf
          weight: 500

    - family: Lobster 1.4
      fonts:
        - asset: assets/fonts/Lobster 1.4.otf
          weight: 400

    - family: Miss Antonia
      fonts:
        - asset: assets/fonts/Miss Antonia.otf
          weight: 400

    - family: Naishila Dancing Script
      fonts:
        - asset: assets/fonts/Naishila Dancing Script.ttf
          weight: 400

    - family: Rick Lobster
      fonts:
        - asset: assets/fonts/Rick Lobster.ttf
          weight: 400

    - family: San Antonio Charros_personal_use_only
      fonts:
        - asset: assets/fonts/San Antonio Charros_personal_use_only.ttf
          weight: 400

    - family: Spiny Lobster DEMO
      fonts:
        - asset: assets/fonts/Spiny Lobster DEMO.ttf
          weight: 400

    - family: Yakuza Lobster
      fonts:
        - asset: assets/fonts/Yakuza Lobster.ttf
          weight: 400