name: LikeChat
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.2.1
  image_picker: ^1.1.2
  video_player: ^2.8.6
  video_thumbnail: ^0.5.3
  chewie: ^1.2.2
  camera: ^0.11.0+1
  image: ^4.2.0
  permission_handler: ^11.3.1
  flutter_volume_controller:
  connectivity: ^3.0.6
  pro_image_editor: ^2.5.8
  iconoir_flutter: ^7.7.0
  flutter_svg: ^2.0.10+1
  volume_controller: ^2.0.7
  lottie: ^3.1.2
  flutter_sliding_up_panel:
  scrollable_positioned_list:
  google_sign_in: ^6.2.1
  network_info_plus: ^5.0.3
  emoji_picker_flutter: ^2.2.0
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  path:
  socket_io_client: ^2.0.3+1
  dio: ^5.4.3+1
  jwt_decoder: ^2.0.1
  image_cropper: ^7.0.5
  dotted_border: ^2.1.0
  flutter_image_filters: ^0.0.19
  share_plus: ^9.0.0
  carousel_slider: ^4.2.1
  video_trimmer: ^2.0.1
  text_editor: ^0.7.0
  file_picker: ^8.0.6
  url_launcher: ^6.3.0
  agora_rtc_engine: ^6.1.0
  pip_view: ^0.9.7
  wakelock_plus: ^1.2.5
  get: ^4.6.5
  contacts_service: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"

flutter:

  uses-material-design: true
  assets:
    - lib/assets/favorite.svg
    - lib/assets/mesage.svg
    - lib/assets/shared.svg
    - lib/assets/logo.png
    - lib/assets/perro.png
    - lib/assets/loading_animation.json
    - lib/assets/logo_google_login.png
    - lib/assets/placeholder_user.jpg
    - lib/assets/emoticon.json
    - lib/assets/emoticon2.json

    - lib/assets/angry.json
    - lib/assets/aplausos.json
    - lib/assets/enamo.json
    - lib/assets/Haja.json
    - lib/assets/heart.json
    - lib/assets/like.json
    - lib/assets/sorpresa.json
    - lib/assets/ultima.json


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

